/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StaffStatus = IDL.Variant({
  'onLeave' : IDL.Null,
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const PriorityLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const ActivityType = IDL.Variant({
  'administrative' : IDL.Null,
  'attendance' : IDL.Null,
  'dataEntry' : IDL.Null,
  'schedule' : IDL.Null,
});
export const ActivityLog = IDL.Record({
  'activityType' : ActivityType,
  'actorName' : IDL.Text,
  'timestamp' : IDL.Int,
  'actionDescription' : IDL.Text,
});
export const Announcement = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Int,
  'author' : IDL.Text,
  'priority' : PriorityLevel,
});
export const StaffRecord = IDL.Record({
  'status' : StaffStatus,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'department' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalClasses' : IDL.Nat,
  'todayAttendancePercentage' : IDL.Float64,
  'activeTeachers' : IDL.Nat,
  'totalStaff' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addStaff' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, StaffStatus], [], []),
  'createAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, PriorityLevel, IDL.Text],
      [],
      [],
    ),
  'getActivityLog' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllAnnouncementsByPriority' : IDL.Func(
      [],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'getAllStaffByDepartment' : IDL.Func([], [IDL.Vec(StaffRecord)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StaffStatus = IDL.Variant({
    'onLeave' : IDL.Null,
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const PriorityLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ActivityType = IDL.Variant({
    'administrative' : IDL.Null,
    'attendance' : IDL.Null,
    'dataEntry' : IDL.Null,
    'schedule' : IDL.Null,
  });
  const ActivityLog = IDL.Record({
    'activityType' : ActivityType,
    'actorName' : IDL.Text,
    'timestamp' : IDL.Int,
    'actionDescription' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Int,
    'author' : IDL.Text,
    'priority' : PriorityLevel,
  });
  const StaffRecord = IDL.Record({
    'status' : StaffStatus,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'department' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalClasses' : IDL.Nat,
    'todayAttendancePercentage' : IDL.Float64,
    'activeTeachers' : IDL.Nat,
    'totalStaff' : IDL.Nat,
  });
  
  return IDL.Service({
    'addStaff' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, StaffStatus], [], []),
    'createAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, PriorityLevel, IDL.Text],
        [],
        [],
      ),
    'getActivityLog' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllAnnouncementsByPriority' : IDL.Func(
        [],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getAllStaffByDepartment' : IDL.Func([], [IDL.Vec(StaffRecord)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };