/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLog {
  'activityType' : ActivityType,
  'actorName' : string,
  'timestamp' : bigint,
  'actionDescription' : string,
}
export type ActivityType = { 'administrative' : null } |
  { 'attendance' : null } |
  { 'dataEntry' : null } |
  { 'schedule' : null };
export interface Announcement {
  'title' : string,
  'content' : string,
  'date' : bigint,
  'author' : string,
  'priority' : PriorityLevel,
}
export interface DashboardStats {
  'totalClasses' : bigint,
  'todayAttendancePercentage' : number,
  'activeTeachers' : bigint,
  'totalStaff' : bigint,
}
export type PriorityLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface StaffRecord {
  'status' : StaffStatus,
  'name' : string,
  'role' : string,
  'department' : string,
}
export type StaffStatus = { 'onLeave' : null } |
  { 'active' : null } |
  { 'inactive' : null };
export interface _SERVICE {
  'addStaff' : ActorMethod<[string, string, string, StaffStatus], undefined>,
  'createAnnouncement' : ActorMethod<
    [string, string, PriorityLevel, string],
    undefined
  >,
  'getActivityLog' : ActorMethod<[], Array<ActivityLog>>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllAnnouncementsByPriority' : ActorMethod<[], Array<Announcement>>,
  'getAllStaffByDepartment' : ActorMethod<[], Array<StaffRecord>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];