/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StaffRecord {
    status: StaffStatus;
    name: string;
    role: string;
    department: string;
}
export interface ActivityLog {
    activityType: ActivityType;
    actorName: string;
    timestamp: bigint;
    actionDescription: string;
}
export interface Announcement {
    title: string;
    content: string;
    date: bigint;
    author: string;
    priority: PriorityLevel;
}
export interface DashboardStats {
    totalClasses: bigint;
    todayAttendancePercentage: number;
    activeTeachers: bigint;
    totalStaff: bigint;
}
export enum ActivityType {
    administrative = "administrative",
    attendance = "attendance",
    dataEntry = "dataEntry",
    schedule = "schedule"
}
export enum PriorityLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum StaffStatus {
    onLeave = "onLeave",
    active = "active",
    inactive = "inactive"
}
export interface backendInterface {
    addStaff(name: string, role: string, department: string, status: StaffStatus): Promise<void>;
    createAnnouncement(title: string, content: string, priority: PriorityLevel, author: string): Promise<void>;
    getActivityLog(): Promise<Array<ActivityLog>>;
    getAllAnnouncements(): Promise<Array<Announcement>>;
    getAllAnnouncementsByPriority(): Promise<Array<Announcement>>;
    getAllStaffByDepartment(): Promise<Array<StaffRecord>>;
    getDashboardStats(): Promise<DashboardStats>;
}
import type { ActivityLog as _ActivityLog, ActivityType as _ActivityType, Announcement as _Announcement, PriorityLevel as _PriorityLevel, StaffRecord as _StaffRecord, StaffStatus as _StaffStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addStaff(arg0: string, arg1: string, arg2: string, arg3: StaffStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStaff(arg0, arg1, arg2, to_candid_StaffStatus_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStaff(arg0, arg1, arg2, to_candid_StaffStatus_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createAnnouncement(arg0: string, arg1: string, arg2: PriorityLevel, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(arg0, arg1, to_candid_PriorityLevel_n3(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(arg0, arg1, to_candid_PriorityLevel_n3(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async getActivityLog(): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLog();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLog();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnouncements();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnouncements();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAnnouncementsByPriority(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnouncementsByPriority();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnouncementsByPriority();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStaffByDepartment(): Promise<Array<StaffRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStaffByDepartment();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStaffByDepartment();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
}
function from_candid_ActivityLog_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLog): ActivityLog {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Announcement_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Announcement): Announcement {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PriorityLevel_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriorityLevel): PriorityLevel {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_StaffRecord_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffRecord): StaffRecord {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_StaffStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffStatus): StaffStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    date: bigint;
    author: string;
    priority: _PriorityLevel;
}): {
    title: string;
    content: string;
    date: bigint;
    author: string;
    priority: PriorityLevel;
} {
    return {
        title: value.title,
        content: value.content,
        date: value.date,
        author: value.author,
        priority: from_candid_PriorityLevel_n13(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _StaffStatus;
    name: string;
    role: string;
    department: string;
}): {
    status: StaffStatus;
    name: string;
    role: string;
    department: string;
} {
    return {
        status: from_candid_StaffStatus_n18(_uploadFile, _downloadFile, value.status),
        name: value.name,
        role: value.role,
        department: value.department
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activityType: _ActivityType;
    actorName: string;
    timestamp: bigint;
    actionDescription: string;
}): {
    activityType: ActivityType;
    actorName: string;
    timestamp: bigint;
    actionDescription: string;
} {
    return {
        activityType: from_candid_ActivityType_n8(_uploadFile, _downloadFile, value.activityType),
        actorName: value.actorName,
        timestamp: value.timestamp,
        actionDescription: value.actionDescription
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): PriorityLevel {
    return "low" in value ? PriorityLevel.low : "high" in value ? PriorityLevel.high : "medium" in value ? PriorityLevel.medium : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    onLeave: null;
} | {
    active: null;
} | {
    inactive: null;
}): StaffStatus {
    return "onLeave" in value ? StaffStatus.onLeave : "active" in value ? StaffStatus.active : "inactive" in value ? StaffStatus.inactive : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    administrative: null;
} | {
    attendance: null;
} | {
    dataEntry: null;
} | {
    schedule: null;
}): ActivityType {
    return "administrative" in value ? ActivityType.administrative : "attendance" in value ? ActivityType.attendance : "dataEntry" in value ? ActivityType.dataEntry : "schedule" in value ? ActivityType.schedule : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Announcement>): Array<Announcement> {
    return value.map((x)=>from_candid_Announcement_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StaffRecord>): Array<StaffRecord> {
    return value.map((x)=>from_candid_StaffRecord_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityLog>): Array<ActivityLog> {
    return value.map((x)=>from_candid_ActivityLog_n6(_uploadFile, _downloadFile, x));
}
function to_candid_PriorityLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriorityLevel): _PriorityLevel {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_StaffStatus_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffStatus): _StaffStatus {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffStatus): {
    onLeave: null;
} | {
    active: null;
} | {
    inactive: null;
} {
    return value == StaffStatus.onLeave ? {
        onLeave: null
    } : value == StaffStatus.active ? {
        active: null
    } : value == StaffStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriorityLevel): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == PriorityLevel.low ? {
        low: null
    } : value == PriorityLevel.high ? {
        high: null
    } : value == PriorityLevel.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
